**ASSIGNMENT 3**

QUESTION 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [ ]:
import numpy as np
arr = np.array(range(2,51,3))
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


QUESTION 2

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
import numpy as np

list1= np.array([1,2,5,446,33])
list2= np.array([23,4522,242,6,1])
print(list1)
print(list2)
list3= np.concatenate((list1,list2))
print (list3)
list4 = np.sort(list3)
print (list4)

[  1   2   5 446  33]
[  23 4522  242    6    1]
[   1    2    5  446   33   23 4522  242    6    1]
[   1    1    2    5    6   23   33  242  446 4522]


QUESTION 3

Write a code snippet to find the dimensions of a ndarray and its size.

In [18]:
import numpy as np
arr = np.arange(24).reshape((2,2,2,3))
print(arr)
print(arr.ndim)
print(arr.size)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]
4
24


QUESTION 4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [26]:
import numpy as np
arr = ([1,2,3,4,5,6,7,8])
arr2 = np.reshape(arr,(2,4))
print (arr2)

[[1 2 3 4]
 [5 6 7 8]]


QUESTION 5

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [28]:
import numpy as np
arr = ([1,2,3,4,5,6,7,8])
arr2 = np.vstack(arr)
print (arr2)
arr3 = np.hstack(arr)
print(arr3)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[1 2 3 4 5 6 7 8]


QUESTION 6

How to get unique items and counts of unique items?

In [31]:
import numpy as np
arr = ([1,2,3,67,67,5],[3,3,2,2,1,5,])
unique = np.unique(arr)
print(unique)

[ 1  2  3  5 67]
